apiVersion: v1
kind: Deployment
metadata:
  name: server
  labels:
    name: server
spec:
  containers:
  - name: server
    imagePullPolicy: IfNotPresent
    image: itaibennatan/psrf:server
  nodeSelector:
    nodename: bob