apiVersion: v1
kind: Pod
metadata:
  name: captain
spec:
  hostname: captain
  containers:
  - name: captain
    imagePullPolicy: Always
    image: itaibennatan/psrf:captain
  nodeSelector:
    debug_handlers: "yes"
