apiVersion: v1
kind: Pod
metadata:
  name: server
  labels:
    name: server
spec:
  containers:
  - name: server
    image: itaibennatan/psrf:server
    ports:
    - containerPort: 8080
  nodeSelector:
    debug_handlers: "no"
