apiVersion: v1
kind: Pod
metadata:
  name: solver
  labels:
    name: solver
spec:
  hostname: solver
  containers:
  - name: solver
    imagePullPolicy: IfNotPresent
    image: itaibennatan/psrf:solver
    ports:
    - containerPort: 1337
  nodeSelector:
<<<<<<< HEAD
    debug_handlers: "no"
=======
    nodename: bob
>>>>>>> 8c07bc488bbc78542128eb24d2f0c84731a5444b
